In [1]:
import numpy as np
import pandas as pd
import pyxlsb

In [2]:
stctvR = pd.read_excel("stc TV Data Set_T3.xlsx")
stctvOG = pd.read_excel("stc TV Data Set_T1.xlsb")

In [3]:
stctvOG.shape

(1048575, 13)

In [4]:
stctvR.shape

(1048575, 6)

In [5]:
stctvR.head()

,Unnamed: 0,user_id_maped,program_name,rating,date_,program_genre
0,0,26138,100 treets,1,2017-05-27,Drama
1,1,7946,Moana,1,2017-05-21,Animation
2,2,7418,The Mermaid Princess,1,2017-08-10,Animation
3,3,19307,The Mermaid Princess,2,2017-07-26,Animation
4,4,15860,Churchill,2,2017-07-07,Biography

In [6]:
stctvR.drop("Unnamed: 0", axis=1, inplace=True)

In [7]:
stctvOG.head()

,Column1,date_,user_id_maped,program_name,duration_seconds,program_class,season,episode,program_desc,program_genre,series_title,hd,original_name
0,1,42882,26138,100 treets,40,MOVIE,0,0,Drama Movie100 Streets,Drama,0,0,100 treets
1,3,42876,7946,Moana,17,MOVIE,0,0,Animation MovieMoana (HD),Animation,0,1,Moana
2,4,42957,7418,The Mermaid Princess,8,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
3,5,42942,19307,The Mermaid Princess,76,MOVIE,0,0,Animation MovieThe Mermaid Princess (HD),Animation,0,1,The Mermaid Princess
4,7,42923,15860,Churchill,87,MOVIE,0,0,Biography MovieChurchill (HD),Biography,0,1,Churchill

In [8]:
stctvR.isnull().any()

user_id_maped    False
program_name     False
rating           False
date_            False
program_genre    False
dtype: bool

In [9]:
stctvOG.drop(["Column1","date_","season", "episode", "series_title","hd","original_name"], axis=1, inplace=True)

In [10]:
stctvOG["program_name"] = stctvOG["program_name"].str.strip()

In [11]:
userProgramRatingMatrix = stctvR.pivot_table(index = "user_id_maped", columns="program_name", values="rating")
userProgramRatingMatrix

program_name,#FollowFriday,10 Days in a Madhouse,100 treets,101 Dalmatians,102 Dalmatians,11.6,12 Monkeys Arms Of Mine,12 Monkeys Atari,12 Monkeys Blood Washed Away,12 Monkeys Bodies Of Water,...,iCarly iLike Jake,iCarly iNevel,iCarly iPilot,iCarly iSpy A Mean Teacher,iCarly iWanna tay With pencer,iCarly iWant A World Record,iCarly iWant More Viewers,iCarly iWill Date Freddie,xXx,xXx: Return of Xander Cage
user_id_maped,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,1.5,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
prog_median_duration = stctvOG.groupby("program_name")["duration_seconds"].median()

In [13]:
stctvOG["watching_rating"] = stctvOG["duration_seconds"] / stctvOG["program_name"].map(prog_median_duration)
stctvOG["watching_rating"].clip(upper=4, inplace=True)

C:\Users\Turki\AppData\Local\Temp\ipykernel_21088\2081812951.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  stctvOG["watching_rating"].clip(upper=4, inplace=True)

In [14]:
stctvOG["watching_rating"] = stctvOG["watching_rating"].round().astype(int)

In [15]:
userProgramDurationMatrix = stctvOG.pivot_table(index="user_id_maped", columns="program_name", values="watching_rating")
userProgramDurationMatrix

program_name,#FollowFriday,10 Days in a Madhouse,100 treets,101 Dalmatians,102 Dalmatians,11.6,12 Monkeys Arms Of Mine,12 Monkeys Atari,12 Monkeys Blood Washed Away,12 Monkeys Bodies Of Water,...,iCarly iLike Jake,iCarly iNevel,iCarly iPilot,iCarly iSpy A Mean Teacher,iCarly iWanna tay With pencer,iCarly iWant A World Record,iCarly iWant More Viewers,iCarly iWill Date Freddie,xXx,xXx: Return of Xander Cage
user_id_maped,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
userProgramRatingMatrix.fillna(0, inplace=True)
userProgramDurationMatrix.fillna(0, inplace=True)

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
similarity_ratings = cosine_similarity(userProgramRatingMatrix.T)
similarity_duration = cosine_similarity(userProgramDurationMatrix.T)

In [25]:
similarity_ratings_df = pd.DataFrame(similarity_ratings, index=userProgramRatingMatrix.columns, columns=userProgramRatingMatrix.columns)
similarity_ratings_df

program_name,#FollowFriday,10 Days in a Madhouse,100 treets,101 Dalmatians,102 Dalmatians,11.6,12 Monkeys Arms Of Mine,12 Monkeys Atari,12 Monkeys Blood Washed Away,12 Monkeys Bodies Of Water,...,iCarly iLike Jake,iCarly iNevel,iCarly iPilot,iCarly iSpy A Mean Teacher,iCarly iWanna tay With pencer,iCarly iWant A World Record,iCarly iWant More Viewers,iCarly iWill Date Freddie,xXx,xXx: Return of Xander Cage
program_name,,,,,,,,,,,,,,,,,,,,,
#FollowFriday,1.000000,0.134575,0.181502,0.072858,0.115202,0.087170,0.016793,0.020947,0.015573,0.012549,...,0.039047,0.033429,0.062857,0.016291,0.029713,0.021416,0.037901,0.020202,0.114522,0.275853
10 Days in a Madhouse,0.134575,1.000000,0.102884,0.060897,0.071505,0.365651,0.008790,0.015836,0.014671,0.017515,...,0.028056,0.031551,0.034046,0.022369,0.026172,0.027610,0.029077,0.036517,0.085545,0.099757
100 treets,0.181502,0.102884,1.000000,0.070282,0.085572,0.081923,0.020976,0.020734,0.019543,0.023660,...,0.026978,0.022111,0.038579,0.014942,0.024673,0.017002,0.032732,0.020365,0.086611,0.217914
101 Dalmatians,0.072858,0.060897,0.070282,1.000000,0.314139,0.022842,0.026974,0.022431,0.000000,0.000000,...,0.137190,0.115932,0.108595,0.086112,0.103984,0.096691,0.120033,0.107704,0.012946,0.048826
102 Dalmatians,0.115202,0.071505,0.085572,0.314139,1.000000,0.060844,0.000000,0.008074,0.000000,0.000000,...,0.056067,0.044678,0.035405,0.040059,0.025208,0.026495,0.061235,0.033717,0.018640,0.068920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
iCarly iWant A World Record,0.021416,0.027610,0.017002,0.096691,0.026495,0.009687,0.020187,0.031709,0.024570,0.030170,...,0.714292,0.778555,0.539604,0.812381,0.816720,1.000000,0.768544,0.837236,0.009689,0.009079
iCarly iWant More Viewers,0.037901,0.029077,0.032732,0.120033,0.061235,0.028585,0.047468,0.046929,0.061625,0.037836,...,0.816712,0.810576,0.599188,0.731438,0.740383,0.768544,1.000000,0.725520,0.043540,0.025332
iCarly iWill Date Freddie,0.020202,0.036517,0.020365,0.107704,0.033717,0.012134,0.046571,0.023832,0.059795,0.042831,...,0.690191,0.779427,0.510195,0.741300,0.758108,0.837236,0.725520,1.000000,0.010316,0.009022
xXx,0.114522,0.085545,0.086611,0.012946,0.018640,0.054329,0.040098,0.055018,0.062468,0.071912,...,0.022792,0.037078,0.049372,0.013457,0.032937,0.009689,0.043540,0.010316,1.000000,0.203760
xXx: Return of Xander Cage,0.275853,0.099757,0.217914,0.048826,0.068920,0.101220,0.057860,0.071422,0.038882,0.043798,...,0.022301,0.017371,0.047851,0.011821,0.016533,0.009079,0.025332,0.009022,0.203760,1.000000

In [26]:
similarity_duration_df = pd.DataFrame(similarity_duration, index=userProgramDurationMatrix.columns , columns=userProgramDurationMatrix.columns)
similarity_duration_df

program_name,#FollowFriday,10 Days in a Madhouse,100 treets,101 Dalmatians,102 Dalmatians,11.6,12 Monkeys Arms Of Mine,12 Monkeys Atari,12 Monkeys Blood Washed Away,12 Monkeys Bodies Of Water,...,iCarly iLike Jake,iCarly iNevel,iCarly iPilot,iCarly iSpy A Mean Teacher,iCarly iWanna tay With pencer,iCarly iWant A World Record,iCarly iWant More Viewers,iCarly iWill Date Freddie,xXx,xXx: Return of Xander Cage
program_name,,,,,,,,,,,,,,,,,,,,,
#FollowFriday,1.000000,0.099792,0.133345,0.043716,0.100057,0.067972,0.006368,0.006404,0.009808,0.003927,...,0.026459,0.027512,0.056811,0.008205,0.014294,0.017192,0.020356,0.011092,0.084103,0.220937
10 Days in a Madhouse,0.099792,1.000000,0.069327,0.055502,0.060439,0.320733,0.003691,0.007423,0.006822,0.012139,...,0.029367,0.031041,0.028486,0.010652,0.027907,0.023516,0.036607,0.033688,0.053293,0.077987
100 treets,0.133345,0.069327,1.000000,0.064199,0.064529,0.050433,0.023220,0.023848,0.019785,0.020311,...,0.019054,0.017076,0.028205,0.010185,0.012063,0.008003,0.026444,0.015777,0.066241,0.161986
101 Dalmatians,0.043716,0.055502,0.064199,1.000000,0.288999,0.002963,0.020521,0.061912,0.000000,0.000000,...,0.129403,0.111419,0.111990,0.069854,0.105599,0.083235,0.103155,0.128090,0.016017,0.031595
102 Dalmatians,0.100057,0.060439,0.064529,0.288999,1.000000,0.027564,0.000000,0.007384,0.000000,0.000000,...,0.044154,0.033740,0.032032,0.024821,0.011798,0.019791,0.054421,0.017906,0.014327,0.034667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
iCarly iWant A World Record,0.017192,0.023516,0.008003,0.083235,0.019791,0.001631,0.008474,0.031245,0.026103,0.020902,...,0.601454,0.689284,0.477780,0.686395,0.692985,1.000000,0.662870,0.703578,0.000000,0.008697
iCarly iWant More Viewers,0.020356,0.036607,0.026444,0.103155,0.054421,0.026952,0.028000,0.062574,0.071878,0.046046,...,0.754205,0.740042,0.545745,0.632983,0.624942,0.662870,1.000000,0.595303,0.029139,0.014370
iCarly iWill Date Freddie,0.011092,0.033688,0.015777,0.128090,0.017906,0.000000,0.041004,0.098967,0.113683,0.080918,...,0.567302,0.666696,0.425828,0.576070,0.640169,0.703578,0.595303,1.000000,0.000000,0.003061
xXx,0.084103,0.053293,0.066241,0.016017,0.014327,0.030066,0.012249,0.024636,0.022639,0.040286,...,0.008438,0.028224,0.041253,0.000000,0.000000,0.000000,0.029139,0.000000,1.000000,0.170818
xXx: Return of Xander Cage,0.220937,0.077987,0.161986,0.031595,0.034667,0.068641,0.037194,0.075546,0.020705,0.026911,...,0.013430,0.015184,0.027819,0.006792,0.006920,0.008697,0.014370,0.003061,0.170818,1.000000

In [ ]:
similarity_ratings_df["Moana"].sort_values(ascending=False).head(6)

program_name
Moana                                    1.000000
Trolls                                   0.572358
Surf's Up : WaveMania                    0.529424
The Mermaid Princess                     0.493362
The Boss Baby                            0.448557
The Jetsons & WWE: Robo-WrestleMania!    0.438942
Name: Moana, dtype: float64

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Moana's top 5 recommendation (Ratings): 
1. Trolls                                   
2. Surf's Up : WaveMania                    
3. The Mermaid Princess                     
4. The Boss Baby                            
5. The Jetsons & WWE: Robo-WrestleMania!

In [28]:
similarity_duration_df["Moana"].sort_values(ascending=False).head(6)

program_name
Moana                    1.000000
Trolls                   0.490425
The Boss Baby            0.418594
Surf's Up : WaveMania    0.411772
The Mermaid Princess     0.404213
Storks                   0.385899
Name: Moana, dtype: float64

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Moana's top 5 recommendation (duration):
1. Trolls                   
2. The Boss Baby            
3. Surf's Up : WaveMania    
4. The Mermaid Princess     
5. Storks

In [31]:
combined_df = (similarity_ratings_df + similarity_duration_df) / 2

In [32]:
combined_df

program_name,#FollowFriday,10 Days in a Madhouse,100 treets,101 Dalmatians,102 Dalmatians,11.6,12 Monkeys Arms Of Mine,12 Monkeys Atari,12 Monkeys Blood Washed Away,12 Monkeys Bodies Of Water,...,iCarly iLike Jake,iCarly iNevel,iCarly iPilot,iCarly iSpy A Mean Teacher,iCarly iWanna tay With pencer,iCarly iWant A World Record,iCarly iWant More Viewers,iCarly iWill Date Freddie,xXx,xXx: Return of Xander Cage
program_name,,,,,,,,,,,,,,,,,,,,,
#FollowFriday,1.000000,0.117183,0.157423,0.058287,0.107629,0.077571,0.011581,0.013675,0.012690,0.008238,...,0.032753,0.030470,0.059834,0.012248,0.022003,0.019304,0.029129,0.015647,0.099312,0.248395
10 Days in a Madhouse,0.117183,1.000000,0.086105,0.058199,0.065972,0.343192,0.006240,0.011630,0.010747,0.014827,...,0.028712,0.031296,0.031266,0.016510,0.027040,0.025563,0.032842,0.035103,0.069419,0.088872
100 treets,0.157423,0.086105,1.000000,0.067241,0.075051,0.066178,0.022098,0.022291,0.019664,0.021986,...,0.023016,0.019593,0.033392,0.012564,0.018368,0.012502,0.029588,0.018071,0.076426,0.189950
101 Dalmatians,0.058287,0.058199,0.067241,1.000000,0.301569,0.012903,0.023748,0.042171,0.000000,0.000000,...,0.133297,0.113676,0.110292,0.077983,0.104791,0.089963,0.111594,0.117897,0.014482,0.040211
102 Dalmatians,0.107629,0.065972,0.075051,0.301569,1.000000,0.044204,0.000000,0.007729,0.000000,0.000000,...,0.050110,0.039209,0.033718,0.032440,0.018503,0.023143,0.057828,0.025811,0.016484,0.051794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
iCarly iWant A World Record,0.019304,0.025563,0.012502,0.089963,0.023143,0.005659,0.014330,0.031477,0.025336,0.025536,...,0.657873,0.733920,0.508692,0.749388,0.754852,1.000000,0.715707,0.770407,0.004845,0.008888
iCarly iWant More Viewers,0.029129,0.032842,0.029588,0.111594,0.057828,0.027769,0.037734,0.054751,0.066752,0.041941,...,0.785459,0.775309,0.572467,0.682211,0.682662,0.715707,1.000000,0.660411,0.036340,0.019851
iCarly iWill Date Freddie,0.015647,0.035103,0.018071,0.117897,0.025811,0.006067,0.043787,0.061399,0.086739,0.061874,...,0.628746,0.723062,0.468012,0.658685,0.699139,0.770407,0.660411,1.000000,0.005158,0.006041
xXx,0.099312,0.069419,0.076426,0.014482,0.016484,0.042198,0.026173,0.039827,0.042554,0.056099,...,0.015615,0.032651,0.045312,0.006728,0.016468,0.004845,0.036340,0.005158,1.000000,0.187289
xXx: Return of Xander Cage,0.248395,0.088872,0.189950,0.040211,0.051794,0.084931,0.047527,0.073484,0.029794,0.035354,...,0.017865,0.016277,0.037835,0.009306,0.011727,0.008888,0.019851,0.006041,0.187289,1.000000

In [33]:
combined_df["Moana"].sort_values(ascending=False).head(6)

program_name
Moana                    1.000000
Trolls                   0.531391
Surf's Up : WaveMania    0.470598
The Mermaid Princess     0.448788
The Boss Baby            0.433575
Storks                   0.404881
Name: Moana, dtype: float64

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Moana's top 5 recommendation ((duration + ratings)/2) :
1. Trolls                  
2. Surf's Up : WaveMania    
3. The Mermaid Princess     
4. The Boss Baby            
5. Storks